### ISSUE TITLE
Apology not accepted

### ISSUE THREAD

**Issue by mikecrinite** [MatthewGimbut/RoomCStudios#1]
https://github.com/MatthewGimbut/RoomCStudios/blob/a471062280a3d318c2c7f2d00f7e968097278c79/index.html#L294

**Comment by mikecrinite** [comment]
I'm bored at work so I'm just going through all my friends' github accounts lol. "Room C Studios" sounded interesting

**Comment by MatthewGimbut** [comment]
oh okay. it was just the website for that game engine i was making when we were still in college

**Comment by mikecrinite** [comment]
Oh okay well you should feel really bad about like 10 `<br/>` tags in a row you stupid idiot
